### ISSUE TITLE
Bug in update-packages.r?

### ISSUE THREAD

**Issue by schiffner** [mllg/travis-r-tools#1]
In l. 19 of https://github.com/rdatsci/travis-r-tools/blob/master/update-packages.r do you mean `e$message` instead of `e`?

```
f = function(x) {
    stop("blub")
}

tryCatch(f(5), error = function(e) cat(e, "/n",  file = stderr()))
Error in cat(list(...), file, sep, fill, labels, append) : 
  argument 1 (type 'list') cannot be handled by 'cat'

tryCatch(f(5), error = function(e) print(str(e)))
List of 2
 $ message: chr "blub"
 $ call   : language f(5)
 - attr(*, "class")= chr [1:3] "simpleError" "error" "condition"
NULL
```

See also https://github.com/mlr-org/mlr-tutorial/issues/28

**Comment by mllg** [comment]
Yep, fixed now. But note that I'm not sure if that calling `update-packages.r` is still required for travis, I think the functionality is now included in devtools.

**Comment by schiffner** [comment]
Thanks. Will look into it.
